import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Butter Chicken Burger',
    description: 'Crispy chicken fillet tossed in rich makhani sauce, served in a brioche bun.',
    price: 14.99,
    category: 'Burgers',
    image: 'https://picsum.photos/seed/burger1/400/300',
    isVeg: false,
    isSpicy: false,
    isChefSpecial: true,
  },
  {
    id: '2',
    name: 'Paneer Tikka Burger',
    description: 'Grilled paneer steak marinated in tandoori spices with mint chutney mayo.',
    price: 12.99,
    category: 'Burgers',
    image: 'https://picsum.photos/seed/burger2/400/300',
    isVeg: true,
    isSpicy: true,
    isChefSpecial: false,
  },
  {
    id: '3',
    name: 'Lamb Rogan Josh',
    description: 'Slow-cooked lamb with aromatic Kashmiri spices and yogurt.',
    price: 18.99,
    category: 'Curries',
    image: 'https://picsum.photos/seed/curry1/400/300',
    isVeg: false,
    isSpicy: true,
    isChefSpecial: true,
  },
  {
    id: '4',
    name: 'Dal Makhani',
    description: 'Black lentils cooked overnight with butter and cream.',
    price: 11.99,
    category: 'Curries',
    image: 'https://picsum.photos/seed/curry2/400/300',
    isVeg: true,
    isSpicy: false,
    isChefSpecial: false,
  },
  {
    id: '5',
    name: 'Garlic Naan',
    description: 'Leavened bread baked in a clay oven topped with garlic and cilantro.',
    price: 3.99,
    category: 'Breads',
    image: 'https://picsum.photos/seed/naan1/400/300',
    isVeg: true,
    isSpicy: false,
    isChefSpecial: false,
  },
  {
    id: '6',
    name: 'Mango Lassi',
    description: 'Refreshing yogurt drink blended with sweet mango pulp.',
    price: 4.99,
    category: 'Drinks',
    image: 'https://picsum.photos/seed/lassi/400/300',
    isVeg: true,
    isSpicy: false,
    isChefSpecial: false,
  },
   {
    id: '7',
    name: 'Samosa Chat',
    description: 'Crushed samosas topped with chickpea curry, chutneys and yogurt.',
    price: 8.99,
    category: 'Appetizers',
    image: 'https://picsum.photos/seed/samosa/400/300',
    isVeg: true,
    isSpicy: true,
    isChefSpecial: false,
  },
  {
    id: '8',
    name: 'Gulab Jamun Cheesecake',
    description: 'Fusion dessert with saffron cheesecake base and gulab jamun chunks.',
    price: 9.99,
    category: 'Desserts',
    image: 'https://picsum.photos/seed/dessert/400/300',
    isVeg: true,
    isSpicy: false,
    isChefSpecial: true,
  },
  {
    id: '9',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with tender chicken, saffron, and whole spices.',
    price: 16.99,
    category: 'Rice',
    image: 'https://picsum.photos/seed/biryani/400/300',
    isVeg: false,
    isSpicy: true,
    isChefSpecial: true,
  },
  {
    id: '10',
    name: 'Paneer Kathi Roll',
    description: 'Spiced paneer cubes wrapped in a paratha with onions and mint sauce.',
    price: 10.99,
    category: 'Rolls',
    image: 'https://picsum.photos/seed/roll/400/300',
    isVeg: true,
    isSpicy: true,
    isChefSpecial: false,
  }
];

export const BRANCHES = [
  { id: 1, name: 'Downtown Main', address: '123 Curry Ave, Food District', phone: '+1 (555) 012-3456' },
  { id: 2, name: 'Westside Mall', address: '456 Mall Rd, Westside', phone: '+1 (555) 012-7890' },
];

export const TESTIMONIALS = [
  { id: 1, name: 'Sarah J.', text: 'The Butter Chicken Burger is a revelation! Best fusion food in town.', rating: 5 },
  { id: 2, name: 'Mike T.', text: 'Fast delivery and the packaging kept everything hot. Highly recommend.', rating: 5 },
  { id: 3, name: 'Priya K.', text: 'Authentic flavors with a modern twist. The ambiance is lovely too.', rating: 4 },
];